name: Run DB Migrations

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: macos-latest
    environment: main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: brew install postgresql

      - name: Make migration script executable
        run: chmod +x ./scripts/run_all.sh

      - name: Run migration scripts
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
          POSTGRES_DATABASE: ${{ vars.POSTGRES_DATABASE }}
        run: ./scripts/run_all.sh
